---
title: "TidyTuesday Global Crop Yields"
output: html_document
---
TidyTuesday Global Crop Yields 2020-09-01 |
[Description](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-09-01/readme.md) |
Contributor: Sabina Rako, Twitter: @ra_sabina]

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidytuesdayR)
library(tidyverse)
library(skimr)
library(ggplot2)
library(forcats)
library(ggsci)
library(ggthemes)
```

## Loading data

```{r cars}
tuesdata <- tidytuesdayR::tt_load('2020-09-01')
fertilizer <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-01/cereal_crop_yield_vs_fertilizer_application.csv')

skim(fertilizer)
```

```{r}
# Preparing data about nitrogen fertilizer use per continent
fertilizerContinent <- fertilizer %>% 
  filter(Entity ==  "Asia" | Entity == "Australia & New Zealand" | Entity == "Americas" | Entity == "Europe" | Entity == "Africa") %>% 
  drop_na(`Nitrogen fertilizer use (kilograms per hectare)`) %>% 
  filter(Year >= 2002) %>% 
  select(Year, Entity, `Nitrogen fertilizer use (kilograms per hectare)`) 

fertilizerContinent$Entity <- as.factor(fertilizerContinent$Entity)
fertilizerContinent <- fertilizerContinent %>% 
  mutate(Entity = forcats::fct_reorder(Entity, desc(`Nitrogen fertilizer use (kilograms per hectare)`)))


ggplot(fertilizerContinent, aes(Year, `Nitrogen fertilizer use (kilograms per hectare)`, color = Entity)) +
  geom_line(size = 1.5) + 
  scale_color_npg() +  
  scale_x_continuous(breaks = seq(2002, 2017, 1), limits=c(2002,2017)) + 
  labs(title= "Nitrogen fertilizer use per continent from 2002 till 2017", caption = "Data source: Our World in Data") + 
  theme_economist_white()+ theme(legend.position="bottom", legend.title = element_blank()) + 
  xlab(label = element_blank()) + 
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)), plot.title = element_text( margin=margin(0,0,20,0)))
    

ggsave("PlotTTw36.png", dpi = 300, height = 10, width = 18, units = "cm")

```


